### ISSUE TITLE
[CUSA02876]: AeternoBlade

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#57]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:M4LYATRhRUE#X#W Lib:libSceNgs2(ver:1) Mod:libSceNgs2(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-142904.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14996722/20240416-142904.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceNgs2RackGetInfo

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error:
```
Critical Error:Exception: reason:0xa0020008 id:0x0
Exiting
```

**Current game status:** Nothing.

**Emulator version:** v.0.5-preview-0
**psOff-libs version:**
8971baae0d5e6cdde85e2c16f062db7aa079804a

Log:
[20240428-023614.000.zip](https://github.com/SysRay/psOff_compatibility/files/15140394/20240428-023614.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error.
```
Error:todo sceNgs2SystemCreate(0000000000000000, 000000000460F9E0, 00000001006947A0)
Error:todo sceNgs2RackCreate(0000000100696A80, 12288, 000000000460F5F8, 000000000460F4C0, 00000001006948A0)
Error:todo sceNgs2RackGetInfo
Error:todo __sce_sigfillset
Error:todo __sce_msync
Error:todo __sce_msync
Error:todo sceKernelDebugRaiseExceptionOnReleaseMode
Error:0x7ff8d41f536c base:0x7ff8d4190000 C:\Windows\System32\KERNELBASE.dll
        RaiseException
Error:0x7ff87f4a23e4 base:0x7ff87f4a0000 E:\PS4\psOff\modules\libkernel.dll
        sceKernelDebugRaiseException (D:\a\psOff_public\psOff_public\modules\libkernel\entry.cpp:320:0)
Error:offset:0x0005fe7a  base:0x20000000        libc.prx
Critical Error:unknown exception at 0x7ff8d41f536c, module base:0x7ff8d4190000 C:\Windows\System32\KERNELBASE.dll
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
4161cbba3b8799559d8c0a5def574f4a6c483caa

Log:
[20240512-110818.000.zip](https://github.com/SysRay/psOff_compatibility/files/15285667/20240512-110818.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
```
libSceNgs2| Error:todo sceNgs2RackGetInfo
libkernel| Error:todo __sce_sigfillset
mman_posix| Error:todo __sce_msync
mman_posix| Error:todo __sce_msync
libkernel| Error:sceKernelDebugRaiseExceptionOnReleaseMode reason:0xa0020008 id:0x0
ExceptionHandler| Error:0x7ffda74e536c base:0x7ffda7480000 C:\Windows\System32\KERNELBASE.dll
        RaiseException
ExceptionHandler| Error:0x7ffd787a24d4 base:0x7ffd787a0000 E:\PS4\psOff\modules\libkernel.dll
        OMDRKKAZ8I4=
ExceptionHandler| Error:offset:0x0005fe7a        base:0x20000000        libc.prx
ExceptionHandler| Critical Error:unknown exception at 0x7ffda74e536c, module base:0x7ffda7480000 C:\Windows\System32\KERNELBASE.dll
Exiting
```
```
ExceptionHandler| Error:0x7ffd72edaf4a base:0x7ffd720b0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
        vkGetInstanceProcAddr
ExceptionHandler| Error:0x7ffd71870505 base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd7187d40f base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd71854237 base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ffd72edaf4a info:0x110000128 , module base:0x7ffd720b0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-142816.000.zip](https://github.com/user-attachments/files/15752495/20240609-142816.000.zip)
