### ISSUE TITLE
[CUSA00709]: OlliOlli2 Welcome to Olliwood

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#61]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:WIWV1Qd7PFU#P#Q Lib:libSceUlt(ver:1) Mod:libSceUlt(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-150515.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14997175/20240416-150515.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceUltWaitingQueueResourcePoolGetWorkAreaSize

**Comment by GamingDucking** [comment]
Retest

**Comment by Emulator-Team-2** [comment]
## Update:

### Please, describe what you get

The game still crashes right after launch.
But now with a different error:
```
Critical Error:QueuePop| queue: 00000000028E3128, data: 0000000043A5FC60
Exiting
Critical Error:QueuePop| queue: 00000000028E3648, data: 0000000044A5FC60
Exiting

Critical Error:Missing Symbol| Name:dmDybN--Fn8#l#f Lib:libSceAjm(ver:1) Mod:libSceAjm(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

5ea4a19d6169e9bfa956279b0844b84949f04418

### Upload your log there

[20240424-181423.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15097474/20240424-181423.000.p7d.zip)

**Comment by GamingDucking** [comment]
Retest

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error:
```
Error:todo sceNpRegisterStateCallback
Error:todo sceNpSetContentRestriction
Critical Error:QueuePop| queue: 0000000100003128, data: 000000000EFBFC60
Exiting
Critical Error:QueuePop| queue: 0000000100003648, data: 000000000FFBFC60
Exiting
```
```
Error:offset:0x0006536c  base:0x7ff879ea0000    C:\Windows\System32\KERNELBASE.dll
Error:offset:0x00006ba7  base:0x7ff85b310000    C:\Windows\SYSTEM32\VCRUNTIME140.dll
Error:offset:0x00003bc4  base:0x7ff85f2a0000    C:\Users\Z490\Desktop\psOff\modules\libSceRtc.dll
Error:offset:0x00003b30  base:0x7ff85f2a0000    C:\Users\Z490\Desktop\psOff\modules\libSceRtc.dll
Critical Error:unknown exception at 0x7ff879f0536c, module base:0x7ff879ea0000 C:\Windows\System32\KERNELBASE.dll
Exiting
```

**Current game status:** Nothing.

**Emulator version:** v.0.5-nightly_29.04.24-fix 
**psOff-libs version:**
ef8106ac3611135c30ef7ac92ec8b11b124b1f11

Log:
[20240502-160505.000.zip](https://github.com/SysRay/psOff_compatibility/files/15189504/20240502-160505.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error.
```
Error:todo constBuffer
Error:todo constBuffer
Error:todo constBuffer
Error:todo constBuffer
Error:todo sceNpRegisterStateCallback
Error:todo sceNpSetContentRestriction
Critical Error:QueuePop| queue: 0000000100003648, data: 000000001D5FFC60
Exiting
Critical Error:QueuePop| queue: 0000000100003128, data: 000000001C5FFC60
Exiting
Error:0x7ff8d41f536c base:0x7ff8d4190000 C:\Windows\System32\KERNELBASE.dll
        RaiseException
Error:0x7ff8b7146ba7 base:0x7ff8b7140000 C:\Windows\SYSTEM32\VCRUNTIME140.dll
        CxxThrowException
Error:0x7ff8b8bb4c84 base:0x7ff8b8bb0000 E:\PS4\psOff\modules\libSceRtc.dll
        boost::throw_exception<boost::gregorian::bad_day_of_month> (D:\a\psOff_public\psOff_public\_build\_Release\third_party\src\third_party\include\boost\throw_exception.hpp:163:0)
Error:0x7ff8b8bb4bfa base:0x7ff8b8bb0000 E:\PS4\psOff\modules\libSceRtc.dll
        boost::CV::constrained_value<boost::CV::simple_exception_policy<unsigned short,1,31,boost::gregorian::bad_day_of_month> >::assign (D:\a\psOff_public\psOff_public\_build\_Release\third_party\src\third_party\include\boost\date_time\constrained_value.hpp:69:0)
Critical Error:unknown exception at 0x7ff8d41f536c, module base:0x7ff8d4190000 C:\Windows\System32\KERNELBASE.dll
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
4161cbba3b8799559d8c0a5def574f4a6c483caa

Log:
[20240512-113040.000.zip](https://github.com/SysRay/psOff_compatibility/files/15285706/20240512-113040.000.zip)
