### ISSUE TITLE
[CUSA01316]: Retro City Rampage™ DX

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#62]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:M4LYATRhRUE#a#V Lib:libSceNgs2(ver:1) Mod:libSceNgs2(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-151426.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14997278/20240416-151426.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceNgs2RackGetInfo

**Comment by Emulator-Team-2** [comment]
## Update:

### Please, describe what you get

The game crashes right after launch with this error:
```
Error:Exception 0x20052af3
Error:0x140022fc7
Error:0x14001eb37
Error:0x140019447
Error:0x140063079
Error:0x7ffe1fd53cff
Error:0x7ffe1fcce456
Error:0x7ffe1fd52cee
Error:0x20052af3          in libc.prx
Error:Access violation: Read 0xffffffffffffffff
```
### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

e7f77e429c3faabb90c3a4021e949fb2ca09c082

### Upload your log there

[20240418-120551.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15023192/20240418-120551.000.p7d.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error.
```
Error:todo sceNgs2SystemCreate(0000000000000000, 00000000044DFB80, 0000000100034320)
Error:todo sceNgs2RackCreate(0000000100036600, 12288, 00000000044DF798, 00000000044DF680, 0000000100034420)
Error:todo sceNgs2RackGetInfo
Error:todo __sce_sigfillset
Error:offset:0x00052af3  base:0x20000000        libc.prx
Critical Error:Access violation: Read at addr:0x20052af3 info:0xffffffffffffffff , module base:0x20000000 libc.prx
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
4161cbba3b8799559d8c0a5def574f4a6c483caa

Log:
[20240512-114727.000.zip](https://github.com/SysRay/psOff_compatibility/files/15285738/20240512-114727.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
```
libSceNgs2| Error:todo sceNgs2RackGetInfo
libkernel| Error:todo __sce_sigfillset
ExceptionHandler| Error:offset:0x00052af3        base:0x20000000        libc.prx
ExceptionHandler| Critical Error:Access violation: Read at addr:0x20052af3 info:0xffffffffffffffff , module base:0x20000000 libc.prx
Exiting
```
```
ExceptionHandler| Error:0x7ffd72edaf4a base:0x7ffd720b0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
        vkGetInstanceProcAddr
ExceptionHandler| Error:0x7ffd71870505 base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd7187d40f base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd71854237 base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ffd72edaf4a info:0x110000128 , module base:0x7ffd720b0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-145402.000.zip](https://github.com/user-attachments/files/15752589/20240609-145402.000.zip)
