### ISSUE TITLE
[CUSA01135]: Trine Enchanted Edition

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#63]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:nXpje5yNpaE#n#l Lib:libSceVoice(ver:1) Mod:libSceVoice(major:0 minor:0)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-152347.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14997426/20240416-152347.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceVoiceCreatePort

**Comment by Emulator-Team-2** [comment]
## Update:

### Please, describe what you get

The game crashes right after launch with this error.
New missing symbol:
```
Critical Error:Missing Symbol| Name:leCAscipfFY#o#m Lib:libSceVideodec(ver:1) Mod:libSceVideodec(major:1 minor:1)
Exiting
```
### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

a2fc208181eff1a38af873a9797f49cea260eb40

### Upload your log there

[20240418-170110.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15026747/20240418-170110.000.p7d.zip)

**Comment by gandalfthewhite19890404** [comment]
Resolved - sceVideodecQueryResourceInfo

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
```
RuntimeLinker| Critical Error:Missing Symbol| Name:leCAscipfFY#o#m Lib:libSceVideodec(ver:1) Mod:libSceVideodec(major:1 minor:1)
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-145737.000.zip](https://github.com/user-attachments/files/15752600/20240609-145737.000.zip)
