### ISSUE TITLE
[CUSA05731]: THE BIT. TRIP

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#64]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:hsKd5c21sQc#i#f Lib:libSceSaveData(ver:1) Mod:libSceSaveData(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-161809.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14998217/20240416-161809.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceSaveDataRegisterEventCallback

**Comment by igor725** [comment]
Should progress further with <https://github.com/SysRay/psOff_public/actions/runs/8772042055>

**Comment by Emulator-Team-2** [comment]
Still crashes right after launch.
But now with a different error:
```
Critical Error:0x00000100 not in m_deviceMemoryList
Exiting
```
Log:
[20240421-125938.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15051620/20240421-125938.000.p7d.zip)

**Comment by igor725** [comment]
Now it's a private part issue, wait til next release

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error:
```
Critical Error:NO Sampled Image 0x00019100 width:2 height:1 type:12 tiling:0x0
Exiting
```

**Current game status:** Nothing.

**Emulator version:** v.0.5-preview-0
**psOff-libs version:**
8971baae0d5e6cdde85e2c16f062db7aa079804a

Log:
[20240428-025557.000.zip](https://github.com/SysRay/psOff_compatibility/files/15140417/20240428-025557.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error.
```
Critical Error:0x00019100 not in m_deviceMemoryList
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_04.05.24
**psOff version:**
cb60bfd95a8f71115db63c56141bfd2c64362936

Log:
[20240504-234747.000.zip](https://github.com/SysRay/psOff_compatibility/files/15211061/20240504-234747.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game now crashes before goes Ingame.
```
libSceNgs2| Error:todo sceNgs2RackGetInfo
```
```
ExceptionHandler| Error:0x7ffd76d63ebc base:0x7ffd76c80000 E:\PS4\psOff\core.dll
        accessRuntimeLinker
ExceptionHandler| Error:0x7ffd76d64100 base:0x7ffd76c80000 E:\PS4\psOff\core.dll
        accessRuntimeLinker
ExceptionHandler| Error:0x7ffd76d64155 base:0x7ffd76c80000 E:\PS4\psOff\core.dll
        accessRuntimeLinker
ExceptionHandler| Error:0x7ffd76c924ba base:0x7ffd76c80000 E:\PS4\psOff\core.dll
        pthread::join
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ffd76d63ebc info:0x0ba38770 , module base:0x7ffd76c80000 E:\PS4\psOff\core.dll
Exiting

ERROR:             vkDestroyDescriptorSetLayout: Invalid device [VUID-vkDestroyDescriptorSetLayout-device-parameter]
```
```
Couldn't Allocate Host Memory: 0x32d040000|8388608 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
ExceptionHandler| Error:offset:0x00030af7        base:0x20000000        libc.prx
ExceptionHandler| Critical Error:Access violation: Write at addr:0x20030af7 info:0x00000000 , module base:0x20000000 libc.prx
Exiting

ERROR:             vkDestroyDescriptorSetLayout: Invalid device [VUID-vkDestroyDescriptorSetLayout-device-parameter]
```

**Current game status:** Intro.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-150601.000.zip](https://github.com/user-attachments/files/15752634/20240609-150601.000.zip)
[20240609-152110.000.zip](https://github.com/user-attachments/files/15752656/20240609-152110.000.zip)

![1](https://github.com/SysRay/psOff_compatibility/assets/38318848/02d53116-4a2d-44e2-976d-0ddd8a366b4f)

## 
Other issues:
- The graphics in the main menu are flickering.
